### ISSUE TITLE
[bug] Note.__getitem__() implementation does not match docstring

### ISSUE THREAD

**Issue by jwhonce** [mm21/trilium-alchemy#1]
docstring:
      """
        Return value of first attribute with provided name, or None if
        no such attribute exists.
        """

code actually raises KeyError when attribute key does not exist.
```python
        # get list of attributes with name
        attrs = self.attributes[key]
```

**Comment by mm21** [comment]
Thanks for catching this. Initially I wanted it to return None, but then realized it should probably be more intuitive dict-like behavior.
